version: '3'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~